<?php

use Hyva\Theme\Model\ViewModelRegistry;
use InPost\InPostPay\ViewModel\Widget;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Widget $widgetViewModel */

$widgetViewModel = $viewModels->require(Widget::class);

$widgetViewModel = $block->getData('widget_view_model');
if (!$widgetViewModel->isEnabled() || !$widgetViewModel->isEnabledOnLoginPage()) {
    return;
}

$bindingPlace = $block->getBindingPlace();
$layoutConfig = $widgetViewModel->getLayoutConfig();
$widgetWrapperClass = "inpay-widget-wrapper";
?>

<?= $block->getChildBlock('inpost.hyva.widget.login.script')->toHtml() ?>

<div x-data="inPostInPostPayHyvaThemeInitializeWidgetLogin"
    @private-content-loaded.window="inPostInPostPayHyvaThemeInitializeWidgetLoginPrivateContentLoadedWindow4"
    class="inpay-login-wrapper">
    <div class="<?= /* @noEscape */ $widgetWrapperClass . ' ' . /* @noEscape */ $bindingPlace?>">
        <inpost-izi-button
            binding_place="<?= /* @noEscape */ $bindingPlace ?>"
            variation="<?= /* @noEscape */ $layoutConfig ?>"
        ></inpost-izi-button>
    </div>
</div>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function inPostInPostPayHyvaThemeInitializeWidgetLogin() {
    return Object.assign(
        initializeInpostPay_<?= $bindingPlace ?>()
        ,{
            ['inPostInPostPayHyvaThemeInitializeWidgetLoginPrivateContentLoadedWindow4'](event) {return this.receiveCustomerData(this.$event.detail.data)},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('inPostInPostPayHyvaThemeInitializeWidgetLogin', inPostInPostPayHyvaThemeInitializeWidgetLogin), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>