<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use InPost\InPostPay\ViewModel\Widget;
use Magento\Framework\View\Element\Template;


/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Widget $widgetViewModel */
/** @var HyvaCsp $hyvaCsp */

$widgetViewModel = $viewModels->require(Widget::class);

$widgetViewModel = $block->getData('widget_view_model');
if (!$widgetViewModel->isEnabled() || !$widgetViewModel->isEnabledOnRegisterPage()) {
    return;
}

$bindingPlace = $block->getBindingPlace();
$layoutConfig = $widgetViewModel->getLayoutConfig();
$widgetWrapperClass = "inpay-widget-wrapper";
?>

<?= $block->getChildBlock('inpost.hyva.widget.register.script')->toHtml() ?>

<div x-data="inPostInPostPayHyvaThemeInitializeWidgetRegister"
     @private-content-loaded.window="inPostInPostPayHyvaThemeInitializeWidgetRegisterPrivateContentLoadedWindow7"
     class="<?= /* @noEscape */
     $widgetWrapperClass . ' ' . /* @noEscape */
     $bindingPlace ?>">
    <inpost-izi-button
        binding_place="<?= /* @noEscape */
        $bindingPlace ?>"
        variation="<?= /* @noEscape */
        $layoutConfig ?>"
    ></inpost-izi-button>
</div>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function inPostInPostPayHyvaThemeInitializeWidgetRegister() {
    return Object.assign(
        initializeInpostPay_<?= $bindingPlace ?>()
        ,{
            ['inPostInPostPayHyvaThemeInitializeWidgetRegisterPrivateContentLoadedWindow7'](event) {return this.receiveCustomerData(this.$event.detail.data)},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('inPostInPostPayHyvaThemeInitializeWidgetRegister', inPostInPostPayHyvaThemeInitializeWidgetRegister), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>
